### PR TITLE
Update to be compatible with BTW CE v1.3.0

### PR DESCRIPTION
**Pull request by Joel-Paul**
Updates CraftGuide to be compatible with BTW CE v1.3.X.

I've rewritten a lot of the code because I didn't like how it was laid out. Personally I think separating the recipes into their own classes looks much neater and is easier to work with.

Uses the new crafting managers for Kiln, Saw, Hopper Filtering, and Piston Packing. I've also manually added the ~~Turntable, Log Chopping,~~ Fishing Rod Baiting, and Knitting Recipes *[EDIT: Turntable and Log Chopping now have crafting managers]*.

I've attached the reobfuscated code in case anyone wants to check it out: [CraftGuide-BTW-CE-v1.3.zip](https://github.com/BTW-Community/CraftGuide/files/8057086/CraftGuide-BTW-CE-v1.3.zip)

TODO:
- Figure out how to determine the input for the Kiln and Saw recipes better. The issue arises from the fact that blocks with various orientations have different Block IDs/metadata values, so they show up as a different recipe. Currently I've gotten around this by using the ItemStack the block drops as the input, however unfired bricks drop clay/sludge so I have to manually modify them. This has potential to cause issues down the line. Vines for some reason drop an Item ID of 0, so that also needs to be manually checked. (Also see https://github.com/BTW-Community/CraftGuide/pull/2#issuecomment-993100793)

- I don't know how to change the color of knitting for the knitting recipes, but that's not a huge issue. I've also not bothered with mixing wool colors for obvious reasons.

- ~~I would like there to be a crafting manager for the Turntable, and maybe even for Villager trading.~~ *[Done! Updated link with these implemented]*

I didn't bother to check if it's compatible with Vanilla because that no longer seems to be important.

### CODE REVIEW

**Comment by ammoore00** [comment]
I can look at tweaking kiln recipes in BTW itself to make it so that different metadata for orientations can be considered the same recipe. Changing the turntable to use a crafting manager is a good idea as well.

Villager trading doesn't use a crafting manager per se, but the trades are all stored as WeightedMerchantEntry objects in lists in FCEntityVillager (tradeByProfessionList and levelUpTradeByProfessionList), which should be accessible.

**Comment by ammoore00** [comment]
To expand a bit on the kiln and saw thing, I can make the recipe also accept an array for the metadata instead of just a single value. That'd also make it easier to define saw recipes for sub-blocks by just having a default array for metadata values that can be passed to generate that.

**Comment by Joel-Paul** [comment]
Cool, I'll have a look at the Villager stuff and see if I can add it. The metadata array would also help.

One thing I forgot to mention is for cake batter for example, the input block is an unfired pottery block with the cake metadata. By taking what the block drops instead, I can set the input to the cake batter item which makes a lot more sense. Do you think you could come up with a solution to that too?

**Comment by ammoore00** [comment]
It'd probably be better to use the result of pick block instead of the block drops, because it won't always drop the same thing in all cases, but pick block should always work for getting the proper item, and that wouldn't require any special casing for stuff like unfired pottery -> baked goods either.

**Comment by Joel-Paul** [comment]
So I just tried using pick block, and they're returning the actual block instead of the ones used, i.e. using pick block on placed ore chunks gives the placed ore block instead of the item, and similarly for the unbaked foods and clay

**Comment by ammoore00** [comment]
> So I just tried using pick block, and they're returning the actual block instead of the ones used, i.e. using pick block on placed ore chunks gives the placed ore block instead of the item, and similarly for the unbaked foods and clay

Noted :) Will get a fix in for that. Anything that does that is a bug, so if you find any more feel free to open an issue over on BTW-Public. Just made an issue for that one: https://github.com/BTW-Community/BTW-Public/issues/138

**Comment by Joel-Paul** [comment]
So `idPicked` works for the most part, but `FCBlockUnfiredPottery` requires you to pass in the world and coordinates to get the metadata for the block, which I can't do

**Comment by ammoore00** [comment]
Issue opened: https://github.com/BTW-Community/BTW-Public/issues/144

**Comment by Joel-Paul** [comment]
I'm using `idPicked` with a try/catch that reverts to `idDropped` if it fails, which I think will be good to keep anyway just in case. So unless you have any suggestions or changes you want made, I think I'm pretty much done.

**Comment by nagalun** [comment]
The textures of the craftguide gui aren't loading with the zip included in the first post, is that a known issue?

**Comment by Joel-Paul** [comment]
No it's not a known issue. I tried it on my end and it seemed to worked fine, could you give some details on how you installed it?

**Comment by nagalun** [comment]
Like this (MultiMC 0.6.13):

image

The generated minecraft.jar does seem to have the images, but they don't load:

image

I don't see anything suspicious on the console logs.

**Comment by Joel-Paul** [comment]
Hmm, I wonder if it's the same issue for why the GUI doesn't show up in the dev environment either. Does the old CraftGuide version on the forums display the GUI properly?

**Comment by nagalun** [comment]
It does, and the images get placed on the same location (/gui/) on the generated jar file:

image

**Comment by Joel-Paul** [comment]
That's annoying, I didn't touch anything related to the GUI at all. Are you using Mac?

**Comment by nagalun** [comment]
No, I'm using Linux. But it also happens to my friend using Windows, he uses MultiMC as well.

**Comment by ammoore00** [comment]
Merging this into its own branch so that others can contribute to the CE update as well

**Comment by Joel-Paul** [comment]
@nagalun Does anything come up in `config/CraftGuide/CraftGuide.log`?

**Comment by nagalun** [comment]
No errors. Does it work for you with MultiMC?

**Comment by Joel-Paul** [comment]
Yeah I’m having no issues on my end using MultiMC. I just realised you didn’t use the original CraftGuide on the latest BTW CE version, could you try that please?

**Comment by nagalun** [comment]
I didn't realize the original zip was compatible with BTW CE. That one does load the textures.

And actually I then tested your craftguide zip after that and it worked without any problems. So I looked for differences and I found out that on first install your zip does not extract theme folders on `config/CraftGuide/themes/`, so the `base`, `dark` and `texpack_support` folders are missing. The original zip does create and populate those folders, and once the original is loaded and the folders are made your version starts working.

**Comment by Joel-Paul** [comment]
Wooo thank you! I'll see if I can fix that ASAP!

**Comment by Joel-Paul** [comment]
Should be fixed now! Just added the `.zip` that gets extracted

**Pull request merged**
